<div class="alert alert-block alert-info" >
    <h1>Robot Perception</h1>
    <h3>General Information:</h3>
    <p>Please do not add or delete any cells. Answers belong into the corresponding cells (below the question). If a function is given (either as a signature or a full function), you should not change the name, arguments or return value of the function.<br><br> If you encounter empty cells underneath the answer that can not be edited, please ignore them, they are for testing purposes.<br><br>When editing an assignment there can be the case that there are variables in the kernel. To make sure your assignment works, please restart the kernel and run all cells before submitting (e.g. via <i>Kernel -> Restart & Run All</i>).</p>
    <p>Code cells where you are supposed to give your answer often include the line  ```raise NotImplementedError```. This makes it easier to automatically grade answers. If you edit the cell please outcomment or delete this line.</p>
    <br>The server resource is limited to 2 core cpu and 1GB RAM at max per user. If you use more than that, the kernel may die. Nevertheless, you can bring it up again by restaring the kernel (Kernel -> Restart and clear output).<br>
    <h3>Submission:</h3>
    <p>Please submit your notebook via the web interface (in the main view -> Assignments -> Submit). The assignments are due on <b>Monday at 0:00.</b> (i.e. Sunday 23:59 + 1 min)</p>
    <h3>Group Work:</h3>
    <p>You are allowed to work in groups of up to two people. Please enter the UID (your username here) of each member of the group into the next cell. We apply plagiarism checking, so do not submit solutions from other people except your team members. If an assignment has a copied solution, the task will be graded with 0 points for all people with the same solution.</p>
    <p><b>YOU SHOULD ONLY SUBMIT EXACTLY ONE PER GROUP</b></p>
    <h3>Questions about the Assignment:</h3>
    <p>If you have questions about the assignment please post them in the LEA forum before the deadline. Don't wait until the last day to post questions.</p></div>

<div class="alert alert-block alert-danger">
<p><b>Put your answer in the PROVIDED CELLS only!</b></p>
<b>Any new cell is not visible during the grading.</b>
<p>We provide additional code and markdown cells for each question, so that you do not have to add the new ones.</p>
<p>Do not copy the metadata from one cell to another, it is unique to that cell only.</p></div>

In [ ]:
'''
Group Work:
Enter the UID (i.e. student2s) of each team member into the variables. 
If you work alone please leave the second variable empty, or extend the list if necessary.
'''
member1 = 'dpadma2s'
member2 = 'jbandl2s'
member3 = 'smuthi2s'

In [ ]:
'''
Put here the average solution time for the full exercise set in estimated MINUTES".
AverageSolutionTimeinMinutes should be > or < 4711
i.e.
AverageSolutionTimeinMinutes = 180
'''

AverageSolutionTimeinMinutes = 840

In [ ]:
# This is a test cell, please ignore it!

## Q&As: Pose three questions (and ans.) to last lecture, 3 Q&As per member [1 point]

The format of the question and answer should be [Q1,A1,Q2,A2,Q3,A3,...,Qn,An], where Q1 is the question and A1 is the answer.<br>
If you work in a group, the total of the Q&As is $3xn$, where $n$ is the total number of members.<br>

Put your answer in the provided cell below!<br>
If you work in a group, you can extend the provided Q&A template, but please use the same format:
1. Q and A are separated by ONE $<$br$>$
2. Q&A and other Q&As are separated by TWO $<$br$>$

Or copy the provided format in the answer cell, and change the Q&A number.
<br>
Do not remove any markdown tag like $<$br$>$ in the answer cell.

<br>
Q1 = Given that only $50 \%$ of point matches are good, and given 4 points picked to estimate homography. How many iterations are needed to have a $95 \%$ probability of success?
<br>
A1 = We know the relationship between the number of trials N, sample size s, outlier ratio e and probability of success p, as given below

$e$ is the probability of outliers

$1-e$ is the probability of inliers

$(1-e)^s$ is the probability of choosing a set of s samples that are all inliers.

$1- (1-e)^s$ is the probability of choosing s points that are NOT all inliers (one of more outliers)

$(1- (1-e)^s)^N$ is the probability of choosing s points N times, and having every set of points include one or more outliers.

Therefore, Probability of choosing s points N times and having one or more sets of all inliers,

\begin{equation}p = 1 - (1-(1-e)^s)^N\end{equation}

In this problem, $\mathrm{e}=.5, s=4,$ and $p=.95$ 

Plugging into the formula, we get:

$1-\left(1-(1-.5)^{4}\right)^{\mathrm{N}}=.95$

Simplify and solve for $\mathrm{N}:$

$$
\begin{array}{l}
1-\left(1-\left(.5^{4}\right)\right)^{\mathrm{N}}=.95 \\
1-(1-.0625)^{\mathrm{N}}=.95 \\
(0.9375)^{\mathrm{N}}=1-.95=.05 \\
\mathrm{N}=\log (.05) / \log (0.9375)=46.4177 \approx47
\end{array}
$$

So, 47 iterations are needed to have a $95 \%$ probability of success [1].

Question Inspiration/Source: https://www.cs.umd.edu/class/spring2018/cmsc426/Assignments/cmsc426_hw1_answer_key.pdf

<br>
<br>
Q2 = Given 100 feature points identified in two images, how many possible combinations of 4 point pairs can one pick?  By what order of magnitude does performing RANSAC improve over brute-force (i.e.  trying all possible 4 point combinations)?
<br>
A2 = 

**Brute-force:**

To brute-force the point matches, we need to pair every possible set of 4-points in each image with each other. This is a combinatorics problem.

For each image, there are $100C_4$ sets of points. Thus there are $(100C_4)^2$ pairings of the sets from both images.

For each pair of 4-point sets, there are 4! ways to match up their points.

Thus the total possible pairings is $(4!) \times (100C_4)^2 = 24\times (3921225)^2 $

The complexity of brute-force problem is:

$100C_4$ is $\frac{100!}{4!\times96!}$ simplifying to (100 x 99 x 98 x 97)/4!. Based on numerator, $nC_k$ is $O(n^4)$. Since we square, $100C_4$ in our problem, brute-forcing complexity if $O(n^8)$ [1].

**RANSAC:**

Let probability  of success = 0.9999 of getting an inlier sample.

We know the relationship between the number of trials N, sample size s, outlier ratio e and probability of success p, as given below:


\begin{equation}p = 1 - (1-(1-e)^s)^N\end{equation}

\begin{equation}\mathrm{N}=\frac{log (1-\mathrm{p})}{log (1-(1-\mathrm{e})^ 4)}\end{equation}

For p = 0.9999 $N \approx \frac{-9.2103}{log(1-(1-e)^4)}$

Number of iterations is a function of e, probability of a point being an outlier.

If e is very bad, say 0.9, then N $\approx$ 90000.

If e is very good, say 0.2, then N $\approx$ 17.

In practice e is rarely bad. Considering the worst case scenario, RANSAC gives atleast 5 order-of-magnitude improvement [1].

Question Inspiration/Source: https://www.cs.umd.edu/class/spring2018/cmsc426/Assignments/cmsc426_hw1_answer_key.pdf
<br>
<br>
Q3 = State the pros, cons and some applications of RANSAC?
<br>
A3 = 

**Good:**

* Robust to outliers.
* Applicable for number of object function parameters of upto $\approx$ 10.
* Applicable for larger number of parameters and parameters are easily obtained than Hough transform [2][3].


**Bad:**

* Computational time grows quickly with fraction of outliers and number of parameters.
* Not good for getting multiple fit [2][3].

**Applications:**

* Computing a homography (e.g., image stitching).
* Estimating fundamental matrix (relating two views).
* Domain plane from a aerial laser scanes.
* Feature-based alignment and feature tracking [2][3].
<br>
<br>

Q4 = How is RANSAC different from conventional smoothing techniques ?

A4 = The RANSAC procedure is opposite to that of conventional smoothing techniques: Rather than using as much of the data as
possible to obtain an initial solution and then attempting to eliminate the invalid data points, RANSAC uses as small an initial data set as feasible and enlarges this set with consistent data when possible

<br>
<br>

Q5 = if two sampled datasets $ s_{1} $ and $ s_{2} $ has equally sized Consensus sets $S_{i}$ and $S_{j}$. How do we chose which sampled set should be used to create the model ?
<br>
A5 = The subset which has smallest standard deviation in the inliers is chose in case of ties.
<br>
<br>
Q6 = What are various RANSAC initilization methods ?
<br>
A6 = An initial estimate for the parametrization may be found by employing a linear technique like DLT algorithm, directly provides H and hence the 9-vector h used to parametrize the iterative minimization. In general if there are n ≥ 4 correspondences, then all will be used in the linear solution.Linear techniques or minimal solutions are the two initialization
techniques recommended in Hartley and Zissermann, 

The other initilization methods are An alternative method that is sometimes used is to carry out a sufficiently dense sampling of parameter space, iterating from each sampled starting point and retaining the best result. This is only possible if the dimension of the parameter space is sufficiently small. Another initialization method is simply to do without any effective initialization at all, starting the iteration at a given fixed point in parameter space. This method is not often viable. Iteration is very likely to fall into a false minimum or not converge. 
<br>
<br>
Q7 = 
<br>
A7 =
<br>
<br>
Q8 = 
<br>
A8 =
<br>
<br>
Q9 = 
<br>
A9 =
<br>
<br>

**Contribution:**

Q1-Q3: dpadma2s

Q4-Q6: jbandl2s

Q7:Q8: smuthi2s

In [ ]:
# This is a test cell, please ignore it!

## Task 1: Implement a base line RANSAC (by hand) to calculate Homography

In [38]:
# YOUR CODE HERE
import numpy as np
import matplotlib.pyplot as plt
import cv2
import random


# def parse_input():
#     p1 = []
#     p2 = []
#     projection_file = open('./boat/homography.txt', mode='r+')
#     line_1 = projection_file.readline()[8:-2].replace(" ", "")
#     line_2 = projection_file.readline()[8:-2].replace(" ", "")

#     line_1 = line_1.split(';')
#     line_2 = line_2.split(';')

#     for i in line_1:
#         i1, i2 = i.split(',')
#         p1.append([int(i1), int(i2)])
#     for i in line_2:
#         i1, i2 = i.split(',')
#         p2.append([int(i1), int(i2)])

#     return np.array(p1), np.array(p2)

def parse_input():
    with open("./boat/homography.txt") as f:
        lines = f.readlines()

    # Get the text coordinates
    lines[0] = lines[0][lines[0].find('[') + 1:lines[0].find(']')]
    lines[1] = lines[1][lines[1].find('[') + 1:lines[1].find(']')]

    # Split coordinate pairs
    lines[0] = lines[0].split(';')
    lines[1] = lines[1].split(';')

    # Map coordinates to 2D int arrays
    x = []
    x_tick = []
    for i in range(len(lines[0])):
        x.append(list(map(int, lines[0][i].split(','))))
        x_tick.append(list(map(int, lines[1][i].split(','))))

    x = np.array(x)
    x_tick = np.array(x_tick)
    return x,x_tick


def normalize(X, to_homog=True):
    mean = np.mean(X, axis=0)
    X_norm = X - mean
    # Average distance to origin
    scale_factor = np.mean(np.sqrt(np.sum(X_norm ** 2, axis=1)))
    scale_factor = np.sqrt(2) / scale_factor
    X_norm = X_norm * scale_factor
    if to_homog:
        X_norm = np.append(X_norm, np.ones((len(X_norm), 1)), axis=1)
    similarity_transform = np.array([[scale_factor, 0, - scale_factor * mean[0]],
                                     [0, scale_factor, - scale_factor * mean[1]],
                                     [0, 0, 1]])

    return similarity_transform, X_norm


def build_A(X, X_tick):
    # Initializations for A matrix
    a_12 = list()
    a_13 = list()
    a_21 = list()
    a_23 = list()
    result = list()

    # Forming A matrix as provided in Reference 1 and Hartley and zisserman multiple view geometry

    for i, j in zip(X, X_tick):
        a_12 = np.array([list(-np.dot(j[2], i.transpose()))])
        a_13 = np.array([list(np.dot(j[1], i.transpose()))])
        a_21 = np.array([list(np.dot(j[2], i.transpose()))])
        a_23 = np.array([list(-np.dot(j[0], i.transpose()))])

        r1 = np.hstack((np.hstack((np.zeros((1, 3)), a_12)), a_13))
        r2 = np.hstack((np.hstack((a_21, np.zeros((1, 3)))), a_23))

        a = np.vstack((r1, r2))

        for k in a:
            result.append(list(k))
    A = np.array(result)
    return A


def get_homography(X, X_tick, to_norm=True):
    if to_norm:
        norm_transform, X = normalize(X)
        norm_transform_tick, X_tick = normalize(X_tick)
    A = build_A(X, X_tick)
    u, s, vt = np.linalg.svd(A, full_matrices=False)
    homography = vt[np.argmin(s)].reshape(3, 3)

    if to_norm:
        homography = np.dot(np.linalg.inv(norm_transform_tick), np.dot(homography, norm_transform))

    homography = homography / homography[2][2]

    return homography


def calculate_transfer_error_symmetric(x, x_tick, homography):
    """
    d = sqrt(d(x, x'.inv(H))^2 + d(x', x.H)^2)
    """
    x_tick_transformed = np.dot(homography, np.append(x, 1.))
    x_transformed = np.dot(np.linalg.inv(homography), np.append(x_tick, 1.))
    squared_distance = euclidean_squared(x, x_transformed[:2]) + euclidean_squared(x_tick, x_tick_transformed[:2])

    return np.sqrt(squared_distance)

def euclidean_squared(x, y):
    """Squared euclidean distance between 2 1D arrays"""
    return np.sum(np.subtract(x, y) ** 2)


def H_from_opencv(p1,p2):
    H, s = cv2.findHomography(p1, p2,cv2.RANSAC, 5)
    return H

class RANSAC:
    def __init__(self, error_threshold, p_outlier, p=0.99, sample_size_min=4, max_iteration_num=100):
        self.error_threshold = error_threshold
        self.p_outlier = p_outlier
        self.min_sample_size = sample_size_min
        self.max_iteration_num = max_iteration_num
        
    def gen_random_indices(self, total_num_sample):
        if self.min_sample_size > total_num_sample:
            return None
        random.seed()
        random_indices = []
        for i in range(self.min_sample_size):
            random_indices.append(random.randint(0, total_num_sample - 1))

        return random_indices
    
    def extract_inliers(self, x, x_tick, homography, sample_num):
        inlier_indices = []
        for j in range(sample_num):
#             print(calculate_transfer_error_symmetric(x[j], x_tick[j], homography))
            if (calculate_transfer_error_symmetric(x[j], x_tick[j], homography)) < self.error_threshold:
                  inlier_indices.append(j)
        return inlier_indices
    
    def calc_homography(self, x, x_tick):
        iteration_num = self.max_iteration_num
        sample_num = len(x)
        inlier_num_threshold = int((1 - self.p_outlier) * sample_num * 0.8)
        print('Number of inlers needed are {}'.format(inlier_num_threshold))
        for i in range(iteration_num):
            random_indices = self.gen_random_indices(sample_num)
            homography = get_homography(x[random_indices], x_tick[random_indices])
            inliers = self.extract_inliers(x, x_tick, homography, sample_num)
            if len(inliers) > inlier_num_threshold:
                print("Returning after {} iternations".format(i))
                return inliers, get_homography(x[inliers], x_tick[inliers])
        print('No sufficient inliers found') 

In [57]:
# YOUR CODE HERE
X, X_tick = parse_input()
H = get_homography(X, X_tick)
H_ocv = H_from_opencv(X, X_tick)
print(H)
print(H_ocv)
average_error = 0.
for i in range(len(X)):
    distance = calculate_transfer_error_symmetric(X[i], X_tick[i], H)
    #print(distance)
    average_error = average_error + distance

average_error = average_error / len(X)
ransac_inst = RANSAC(average_error*13.5,0.4)
inliers, ransac_homography = ransac_inst.calc_homography(X, X_tick)
print(len(inliers))
print(ransac_homography)

[[ 8.75450973e-01  2.32382658e-01  3.46996190e+00]
 [-2.14134751e-01  8.79256777e-01  1.29608155e+02]
 [ 1.10832036e-05  3.04033707e-05  1.00000000e+00]]
[[ 8.75621247e-01  2.32487163e-01  3.42174345e+00]
 [-2.14118735e-01  8.79376769e-01  1.29602218e+02]
 [ 1.12366054e-05  3.05886233e-05  1.00000000e+00]]
Number of inlers needed are 12
Returning after 82 iternations
23
[[ 8.75010023e-01  2.23010631e-01  5.01519929e+00]
 [-2.13057706e-01  8.72181133e-01  1.30278998e+02]
 [ 1.43922395e-05  1.48898458e-05  1.00000000e+00]]


YOUR ANSWER HERE

YOUR ANSWER HERE

## Task 2: Compare your new RANSAC algorithm

### a) Compare your new RANSAC algorithm to your hand made DLT

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

YOUR ANSWER HERE

YOUR ANSWER HERE

### b) Compare your new RANSAC algorithm to a handmade normalised DLT

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

YOUR ANSWER HERE

YOUR ANSWER HERE

### c) Compare your new RANSAC algorithm to a library RANSAC implementation.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

YOUR ANSWER HERE

YOUR ANSWER HERE

References:
    
1. Yiannis Aloimonos, Jack Rasiel, and Kaan Elgin, CMSC 426 Computer Vision Homework 1, Accessed on: 04.05.2020 [Online], URL: https://www.cs.umd.edu/class/spring2018/cmsc426/Assignments/cmsc426_hw1_answer_key.pdf.
2. Kris Kitani, RANSAC, 16-385 Computer Vision, Carnegie Mellon University, Accessed on: 04.05.2020 [Online], URL: http://www.cs.cmu.edu/~16385/s17/Slides/10.3_2D_Alignment__RANSAC.pdf.
3. Cyrill Stachniss, Photogrammetry II Chapter SIFT features and RANSAC, University of Bonn, Accessed on: 04.05.2020 [Online], URL: https://www.youtube.com/watch?v=oT9c_LlFBqs.